apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - match:
        - headers:
            end-user:
              exact: tim
      route:
        - destination:
            host: reviews
            subset: v2
    - match:
        - headers:
            end-user:
              exact: joe
      route:
        - destination:
            host: reviews
            subset: v2
      fault:
        abort:
          percent: 100
          httpStatus: 500
    - route:
        - destination:
            host: reviews
            subset: v1
